title: Diogo Seca
description: > # this means to ignore newlines until "baseurl:"
  I'm Diogo, a machine learning researcher with an obsession for
  quantitative investing. My specialty is time series forecasting.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "diogoseca.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: "https://twitter.com/BayesTheQuant" #if your site has a twitter account, enter it here

# Author Settings
author: Diogo Seca # add your name
author-img: diogo-seca.jpg # add your photo
about-author: >
  I'm a Machine Learning Researcher obsessed with Forecasting and Quantitative Investing. 
  My greatest gifts are my curiosity and my critical thinking.
social-twitter: "https://twitter.com/BayesTheQuant" # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: "https://github.com/diogoseca" # add your Github handle
social-linkedin: "https://www.linkedin.com/in/diogoseca" # add your Linkedin handle
social-email: "diogoseca@gmail.com" # add your Email address

# Disqus
discus-identifier: diogoseca # add your discus identifier

# Tracker
analytics: UA-113445569-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
