title: Diogo Seca
description: > # this means to ignore newlines until "baseurl:"
  Welcome! I'm Diogo, a machine learning researcher with an obsession 
  for quantitative investing. This blog is a collection of topics that
  fascinate me.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "diogoseca.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: "" #if your site has a twitter account, enter it here

# Author Settings
author: Diogo Seca # add your name
author-img: diogo-seca.png # add your photo
about-author: 
  Welcome to my blog! 
  I'm a Machine Learning Researcher obsessed with Forecasting and Quantitative Investing.
social-facebook: # add your Facebook handle
social-github: diogoseca # add your Github handle
social-linkedin: diogoseca # add your Linkedin handle
social-email: diogoseca@gmail.com # add your Email address

# Disqus
discus-identifier: diogoseca-com # add your discus identifier

# Tracker
analytics: UA-113445569-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-jupyter-notebook

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
